function monthlymilkproductionpoundsp1 = importfile(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as a matrix.
%   MONTHLYMILKPRODUCTIONPOUNDSP1 = IMPORTFILE(FILENAME) Reads data from
%   text file FILENAME for the default selection.
%
%   MONTHLYMILKPRODUCTIONPOUNDSP1 = IMPORTFILE(FILENAME, STARTROW, ENDROW)
%   Reads data from rows STARTROW through ENDROW of text file FILENAME.
%
% Example:
%   monthlymilkproductionpoundsp1 = importfile('monthly-milk-production-pounds-p.csv', 2, 157);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2019/01/19 16:50:17

%% Initialize variables.
delimiter = ',';
if nargin<=2
    startRow = 2;
    endRow = 157;
end

%% Format for each line of text:
%   column1: text (%q)
%	column2: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%q%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
textscan(fileID, '%[^\n\r]', startRow(1)-1, 'WhiteSpace', '', 'ReturnOnError', false);
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'TextType', 'string', 'ReturnOnError', false, 'EndOfLine', '\r\n');
for block=2:length(startRow)
    frewind(fileID);
    textscan(fileID, '%[^\n\r]', startRow(block)-1, 'WhiteSpace', '', 'ReturnOnError', false);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'TextType', 'string', 'ReturnOnError', false, 'EndOfLine', '\r\n');
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
dataArray(2) = cellfun(@(x) num2cell(x), dataArray(2), 'UniformOutput', false);
dataArray(1) = cellfun(@(x) mat2cell(x, ones(length(x), 1)), dataArray(1), 'UniformOutput', false);
monthlymilkproductionpoundsp1 = [dataArray{1:end-1}];
